export type MenuItem = {
  id: number;
  name: string;
  category: string;
  price: number | null;
  image: string;
  description?: string;
  items?: string[];
  isVeg: boolean;
};

export const categories = [
  "All",
  "Tandoori Roti",
  "Soup",
  "Chinese Veg Starter",
  "Chinese Rice & Noodles",
  "Dessert",
  "Fresh Fruit Juice",
  "Real Packed Juice Glass",
  "Real Dal Spice",
  "Spice Rice and Biryani",
  "Veg Tandoori Starter",
  "Real Spice Paneer Special",
  "pantry"
];

export const menuItems: MenuItem[] = [
  { id: 1, name: "Masala Papad", category: "pantry", price: 40, image: "/images/masala-papad.png", description: "Crispy papad with masala seasoning.", isVeg: true },
  { id: 2, name: "Fry Papad", category: "pantry", price: 25, image: "/images/fry-papad.png", description: "Light and crispy fried papad.", isVeg: true },
  { id: 3, name: "Roasted Papad", category: "pantry", price: 20, image: "/images/roasted-papad.png", description: "Gently roasted papad.", isVeg: true },
  { id: 4, name: "Chole Bature", category: "pantry", price: 130, image: "/images/chole-bhature.png", description: "Fluffy deep-fried bread with spiced chickpea curry.", isVeg: true },
  { id: 5, name: "Pav Bhaji", category: "pantry", price: 150, image: "/images/pav-bhaji.png", description: "Mumbai-style spiced mashed vegetables with butter pav.", isVeg: true },
  { id: 6, name: "Aalo Paratha", category: "pantry", price: 150, image: "/images/aalo-paratha.png", description: "Potato-stuffed Indian bread, 2 pieces.", isVeg: true },
  { id: 7, name: "Butter Milk", category: "pantry", price: 30, image: "/images/butter-milk.png", description: "Fresh chilled buttermilk.", isVeg: true },
  { id: 8, name: "Boondi Raita", category: "pantry", price: 70, image: "/images/boondi-raita.png", description: "Yogurt with boondi (tiny fried gram flour balls).", isVeg: true },
  { id: 9, name: "Veg Raita", category: "pantry", price: 70, image: "/images/veg-raita.png", description: "Yogurt with mixed vegetables.", isVeg: true },
  { id: 10, name: "Green Salad", category:"pantry", price: 90, image: "/images/green-salad.png", description: "Fresh seasonal green salad.", isVeg: true },
  { id: 11, name: "Finger Chips", category: "pantry", price: 100, image: "/images/finger-chips.png", description: "Crispy golden potato fries.", isVeg: true },
  { id: 12, name: "Plain Lassi", category: "pantry", price: 50, image: "/images/plain-lassi.png", description: "Traditional yogurt drink.", isVeg: true },
  { id: 13, name: "Patiala Lassi", category: "pantry", price: 100, image: "/images/patiala-lassi.png", description: "Rich and creamy Patiala-style lassi.", isVeg: true },
  { id: 14, name: "Mango Lassi", category: "pantry", price: 70, image: "/images/mango-lassi.png", description: "Creamy yogurt drink with ripe mango.", isVeg: true },
  { id: 15, name: "Strawberry Lassi", category: "pantry", price: 70, image: "/images/strawberry-lassi.png", description: "Refreshing strawberry yogurt drink.", isVeg: true },
  { id: 16, name: "Dry Fruit Lassi", category: "pantry", price: 90, image: "/images/dry-fruit-lassi.png", description: "Lassi enriched with dry fruits and nuts.", isVeg: true },
  { id: 17, name: "Oreo Shake", category: "pantry", price: 100, image: "/images/oreo-shake.png", description: "Creamy shake with crushed Oreo cookies.", isVeg: true },
  { id: 18, name: "Chocolate Shake", category: "pantry", price: 100, image: "/images/chocolate-shake.png", description: "Rich and indulgent chocolate milkshake.", isVeg: true },
  { id: 19, name: "Cold Coffee", category: "pantry",price: 80, image: "/images/cold-coffee.png", description: "Chilled coffee with milk and ice.", isVeg: true },
  { id: 20, name: "Tea", category: "pantry", price: 30, image: "/images/tea.png", description: "Hot Indian tea.", isVeg: true },
  { id: 21, name: "Hot Coffee", category: "pantry", price: 50, image: "/images/hot-coffee.png", description: "Freshly brewed hot coffee.", isVeg: true },
  { id: 22, name: "Hot Milk", category: "pantry", price: 60, image: "/images/hot-milk.png", description: "Hot steamed milk.", isVeg: true },
  { id: 23, name: "Mint Mojito", category: "pantry", price: 150, image: "/images/mint-mojito.png", description: "Refreshing mint mojito with lime and soda.", isVeg: true },
  { id: 24, name: "Fresh Lime Soda", category: "pantry", price: 50, image: "/images/fresh-lime-soda.png", description: "Tangy fresh lime soda.", isVeg: true },
  { id: 25, name: "Dahi", category: "pantry", price: 50, image: "/images/dahi.png", description: "Fresh homemade yogurt.", isVeg: true },

  { id: 26, name: "Chapati", category: "Tandoori Roti", price: 15, image: "/images/chapati.png", description: "Freshly made whole wheat chapati.", isVeg: true },
  { id: 27, name: "Butter Chapati", category: "Tandoori Roti", price: 20, image: "/images/butter-chapati.png", description: "Chapati brushed with butter.", isVeg: true },
  { id: 28, name: "Roti", category: "Tandoori Roti", price: 20, image: "/images/rotiii.png", description: "Soft tandoori roti.", isVeg: true },
  { id: 29, name: "Butter Roti", category: "Tandoori Roti", price: 30, image: "/images/butter-rotiii.png", description: "Roti with butter.", isVeg: true },
  { id: 30, name: "Kulcha", category: "Tandoori Roti", price: 30, image: "/images/kulcha.png", description: "Stuffed or plain kulcha.", isVeg: true },
  { id: 31, name: "Butter Kulcha", category: "Tandoori Roti", price: 40, image: "/images/butter-kulcha.png", description: "Buttery kulcha.", isVeg: true },
  { id: 32, name: "Paratha", category: "Tandoori Roti", price: 40, image: "/images/paratha.png", description: "Layered paratha.", isVeg: true },
  { id: 33, name: "Butter Paratha", category: "Tandoori Roti", price: 50, image: "/images/butter-paratha.png", description: "Paratha with butter.", isVeg: true },
  { id: 34, name: "Naan", category: "Tandoori Roti", price: 40, image: "/images/naan.png", description: "Soft tandoori naan.", isVeg: true },
  { id: 35, name: "Butter Naan", category: "Tandoori Roti", price: 50, image: "/images/butter-naan.png", description: "Naan with butter.", isVeg: true },
  { id: 36, name: "Garlic Naan", category: "Tandoori Roti", price: 70, image: "/images/garlic-naan.png", description: "Naan topped with garlic.", isVeg: true },
  { id: 37, name: "Butter Garlic Naan", category: "Tandoori Roti", price: 90, image: "/images/butter-garlic-naan.png", description: "Garlic naan with extra butter.", isVeg: true },
  { id: 38, name: "Cheese Naan", category: "Tandoori Roti", price: 115, image: "/images/cheese-naan.png", description: "Naan stuffed with cheese.", isVeg: true },
  { id: 39, name: "Cheese Garlic Naan", category: "Tandoori Roti", price: 120, image: "/images/cheese-garlic-naan.png", description: "Garlic naan stuffed with cheese.", isVeg: true },
  { id: 40, name: "Missi Roti", category: "Tandoori Roti", price: 50, image: "/images/missi-roti.png", description: "Protein-rich missi roti.", isVeg: true },
  { id: 41, name: "Butter Missi Roti", category: "Tandoori Roti", price: 60, image: "/images/butter-missi-roti.png", description: "Missi roti with butter.", isVeg: true },
  { id: 42, name: "Butter Aloo Paratha", category: "Tandoori Roti", price: 100, image: "/images/butter-aloo-paratha.png", description: "Potato-stuffed paratha with butter.", isVeg: true },
  { id: 43, name: "Paneer Paratha", category: "Tandoori Roti", price: 120, image: "/images/paneer-paratha.png", description: "Paneer-stuffed paratha.", isVeg: true },
  { id: 44, name: "Stuff Paratha", category: "Tandoori Roti", price: 130, image: "/images/stuff-paratha.png", description: "Assorted stuffed paratha.", isVeg: true },
  { id: 45, name: "Lacha Paratha", category: "Tandoori Roti", price: 150, image: "/images/lacha-paratha.png", description: "Layered lacha paratha.", isVeg: true },
  { id: 46, name: "Real Spice Basket Roti", category: "Tandoori Roti", price: 300, image: "/images/basket-roti.png", description: "Signature basket of rotis.", isVeg: true },
  { id: 47, name: "Makai Roti", category: "Tandoori Roti", price: 30, image: "/images/makai-roti.png", description: "Corn flour roti.", isVeg: true },
  { id: 48, name: "Bajra Roti", category: "Tandoori Roti", price: 30, image: "/images/bajra-roti.png", description: "Pearl millet roti.", isVeg: true },

  { id: 49, name: "Manchow Soup", category: "Soup", price: 120, image: "/images/manchow-soup.png", description: "Warm and spicy Manchow soup.", isVeg: true },
  { id: 50, name: "Tomato Soup", category: "Soup", price: 110, image: "/images/tomato-soup.png", description: "Classic tomato soup.", isVeg: true },
  { id: 51, name: "Hot & Sour Soup", category: "Soup", price: 130, image: "/images/hot-sour-soup.png", description: "Tangy hot and sour soup.", isVeg: true },
  { id: 52, name: "Lemon Coriander Soup", category: "Soup", price: 130, image: "/images/lemon-coriander-soup.png", description: "Zesty lemon coriander soup.", isVeg: true },

  { id: 53, name: "Chilly Potato", category: "Chinese Veg Starter", price: 190, image: "/images/chilly-potato.png", description: "Spicy chilly potatoes.", isVeg: true },
  { id: 54, name: "Paneer Chilly Dry", category: "Chinese Veg Starter", price: 210, image: "/images/paneer-chilly-dry.png", description: "Dry chilly paneer.", isVeg: true },
  { id: 55, name: "Paneer Chilly Gravy", category: "Chinese Veg Starter", price: 230, image: "/images/paneer-chilly-gravy.png", description: "Paneer in schezwan gravy.", isVeg: true },
  { id: 56, name: "Paneer 65", category: "Chinese Veg Starter", price: 230, image: "/images/paneer-65.png", description: "Crispy paneer 65.", isVeg: true },
  { id: 57, name: "Paneer Crispy", category: "Chinese Veg Starter", price: 230, image: "/images/paneer-crispy.png", description: "Crispy fried paneer.", isVeg: true },
  { id: 58, name: "Veg Crispy", category: "Chinese Veg Starter", price: 190, image: "/images/veg-crispy.png", description: "Mixed veg crispy.", isVeg: true },
  { id: 59, name: "Veg Manchurian", category: "Chinese Veg Starter", price: 190, image: "/images/veg-manchurian.png", description: "Veg manchurian in sauce.", isVeg: true },
  { id: 60, name: "Mushroom", category: "Chinese Veg Starter", price: 230, image: "/images/mushroom.png", description: "Mushroom starter.", isVeg: true },
  { id: 61, name: "Mushroom Chilly", category: "Chinese Veg Starter", price: 230, image: "/images/mushroom-chilly.png", description: "Mushroom chilly.", isVeg: true },
  { id: 62, name: "Chinese Sizzler", category: "Chinese Veg Starter", price: 550, image: "/images/chinese-sizzler.png", description: "Hot Chinese sizzler platter.", isVeg: true },

  { id: 63, name: "Fried Rice", category: "Chinese Rice & Noodles", price: 220, image: "/images/fried-rice.png", description: "Vegetable fried rice.", isVeg: true },
  { id: 64, name: "Schezwan Rice", category: "Chinese Rice & Noodles", price: 240, image: "/images/schezwan-rice.png", description: "Spicy schezwan fried rice.", isVeg: true },
  { id: 65, name: "Tripple Schezwan Rice", category: "Chinese Rice & Noodles", price: 280, image: "/images/tripple-schezwan-rice.png", description: "Extra spicy schezwan rice.", isVeg: true },
  { id: 66, name: "Manchurian Rice", category: "Chinese Rice & Noodles", price: 260, image: "/images/manchurian-rice.png", description: "Manchurian tossed rice.", isVeg: true },
  { id: 67, name: "Hakka Noodles", category: "Chinese Rice & Noodles", price: 220, image: "/images/hakka-noodles.png", description: "Classic hakka noodles.", isVeg: true },
  { id: 68, name: "Schezwan Noodles", category: "Chinese Rice & Noodles", price: 230, image: "/images/schezwan-noodles.png", description: "Schezwan flavored noodles.", isVeg: true },
  { id: 69, name: "Tripple Schezwan Noodles", category: "Chinese Rice & Noodles", price: 280, image: "/images/tripple-schezwan-noodles.png", description: "Extra spicy schezwan noodles.", isVeg: true },

  { id: 70, name: "Gulab Jamun (2 Piece)", category: "Dessert", price: 50, image: "/images/gulab-jamun.png", description: "Soft syrupy gulab jamun.", isVeg: true },
  { id: 71, name: "Vanilla Ice Cream", category: "Dessert", price: 30, image: "/images/vanilla-ice-cream.png", description: "Classic vanilla scoop.", isVeg: true },
  { id: 72, name: "Chocolate Ice Cream", category: "Dessert", price: 40, image: "/images/chocolate-ice-cream.png", description: "Rich chocolate ice cream.", isVeg: true },
  { id: 73, name: "Fruit Salad", category: "Dessert", price: 50, image: "/images/fruit-salad.png", description: "Fresh mixed fruit salad.", isVeg: true },

  { id: 74, name: "Orange Juice", category: "Fresh Fruit Juice", price: 120, image: "/images/orange-juice.png", description: "Freshly squeezed orange juice.", isVeg: true },
  { id: 75, name: "Pineapple Juice", category: "Fresh Fruit Juice", price: 120, image: "/images/pineapple-juice.png", description: "Fresh pineapple juice.", isVeg: true },

  { id: 76, name: "Mix Fruit Juice Glass", category: "Real Packed Juice Glass", price: 80, image: "/images/mix-fruit-juice.png", description: "Packaged mix fruit juice glass.", isVeg: true },
  { id: 77, name: "Dragon Juice Glass", category: "Real Packed Juice Glass", price: 80, image: "/images/dragon-juice.png", description: "Dragon fruit packed juice.", isVeg: true },
  { id: 78, name: "Mango Juice Glass", category: "Real Packed Juice Glass", price: 80, image: "/images/mango-juice.png", description: "Packaged mango juice.", isVeg: true },
  { id: 79, name: "Can Berry Juice Glass", category: "Real Packed Juice Glass", price: 100, image: "/images/can-berry-juice.png", description: "Packaged berry juice.", isVeg: true },

  { id: 80, name: "Dal Fry", category: "Real Dal Spice", price: 120, image: "/images/dal-fry.png", description: "Homestyle dal fry.", isVeg: true },
  { id: 81, name: "Dal Tadka", category: "Real Dal Spice", price: 140, image: "/images/dal-tadka.png", description: "Tempered dal tadka.", isVeg: true },
  { id: 82, name: "Dal Palak", category: "Real Dal Spice", price: 160, image: "/images/dal-palak.png", description: "Dal cooked with spinach.", isVeg: true },
  { id: 83, name: "Dal Makhani", category: "Real Dal Spice", price: 200, image: "/images/dal-makhani.png", description: "Creamy dal makhani.", isVeg: true },

  { id: 84, name: "Steam Rice", category: "Spice Rice and Biryani", price: 130, image: "/images/steam-rice.png", description: "Steamed basmati rice.", isVeg: true },
  { id: 85, name: "Jeera Rice", category: "Spice Rice and Biryani", price: 150, image: "/images/jeera-rice.png", description: "Cumin flavored rice.", isVeg: true },
  { id: 86, name: "Masala Rice", category: "Spice Rice and Biryani", price: 150, image: "/images/masala-rice.png", description: "Spiced vegetable rice.", isVeg: true },
  { id: 87, name: "Veg Biryani", category: "Spice Rice and Biryani", price: 180, image: "/images/veg-biryani.png", description: "Layered vegetable biryani.", isVeg: true },
  { id: 88, name: "Veg Pulav", category: "Spice Rice and Biryani", price: 190, image: "/images/veg-pulav.png", description: "Aromatic veg pulav.", isVeg: true },
  { id: 89, name: "Kashmiri Pulav (Sweet)", category: "Spice Rice and Biryani", price: 200, image: "/images/kashmiri-pulav.png", description: "Sweet nutty Kashmiri pulav.", isVeg: true },
  { id: 90, name: "Veg Hyderabadi Dum Biryani", category: "Spice Rice and Biryani", price: 250, image: "/images/dum-biryani.png", description: "Hyderabadi style dum biryani.", isVeg: false},
  { id: 91, name: "Dum Biryani", category: "Spice Rice and Biryani", price: 280, image: "/images/dum-biryani.png", description: "Hearty dum biryani.", isVeg: true },
  { id: 92, name: "Matka Biryani", category: "Spice Rice and Biryani", price: 300, image: "/images/matka-biryani.png", description: "Claypot matka biryani.", isVeg: true },
  { id: 93, name: "Cheese Pulao", category: "Spice Rice and Biryani", price: 250, image: "/images/cheese-pulao.png", description: "Cheesy pulao.", isVeg: true },
  { id: 94, name: "Dal Khichdi", category: "Spice Rice and Biryani", price: 150, image: "/images/dal-khichdi.png", description: "Comforting dal khichdi.", isVeg: true },
  { id: 95, name: "Palak Khichdi", category: "Spice Rice and Biryani", price: 160, image: "/images/palak-khichdi.png", description: "Spinach khichdi.", isVeg: true },
  { id: 96, name: "Palak Tadka Khichdi", category: "Spice Rice and Biryani", price: 160, image: "/images/palak-tadka-khichdi.png", description: "Palak khichdi with tadka.", isVeg: true },

  { id: 97, name: "Paneer Tikka", category: "Veg Tandoori Starter", price: 240, image: "/images/paneer-tikka.png", description: "Marinated paneer tikka.", isVeg: true },
  { id: 98, name: "Paneer Malai Tikka", category: "Veg Tandoori Starter", price: 260, image: "/images/paneer-malai-tikka.png", description: "Creamy malai paneer tikka.", isVeg: true },
  { id: 99, name: "Paneer Kalimirch Tikka", category: "Veg Tandoori Starter", price: 260, image: "/images/paneer-kalimirch-tikka.png", description: "Paneer with black pepper.", isVeg: true },
  { id: 100, name: "Paneer Afghani Tikka", category: "Veg Tandoori Starter", price: 270, image: "/images/paneer-afghani-tikka.png", description: "Afghani style paneer tikka.", isVeg: true },
  { id: 101, name: "Paneer Pahadi Tikka", category: "Veg Tandoori Starter", price: 270, image: "/images/paneer-pahadi-tikka.png", description: "Pahadi masala paneer tikka.", isVeg: true },
  { id: 102, name: "Paneer Seekh Kabab", category: "Veg Tandoori Starter", price: 270, image: "/images/paneer-seekh-kabab.png", description: "Paneer seekh style kabab.", isVeg: false },
  { id: 103, name: "Lahsoni Tikka", category: "Veg Tandoori Starter", price: 270, image: "/images/lahsoni-tikka.png", description: "Garlic-flavored tikka.", isVeg: true },
  { id: 104, name: "Mushroom Tikka", category: "Veg Tandoori Starter", price: 260, image: "/images/mushroom-tikka.png", description: "Grilled mushroom tikka.", isVeg: true },
  { id: 105, name: "Corn Tikka", category: "Veg Tandoori Starter", price: 260, image: "/images/corn-tikka.png", description: "Corn tikka.", isVeg: true },
  { id: 106, name: "Soya Chhap Tikka", category: "Veg Tandoori Starter", price: 260, image: "/images/soya-chhap-tikka.png", description: "Soya chhap tikka.", isVeg: true },
  { id: 107, name: "Hara Bhara Kabab", category: "Veg Tandoori Starter", price: 230, image: "/images/hara-bhara-kabab.png", description: "Spinach and peas kabab.", isVeg: false },
  { id: 108, name: "Real Spice Veg Plater", category: "Veg Tandoori Starter", price: 800, image: "/images/real-spice-veg-platter.png", description: "Assorted veg starter platter.", isVeg: true },

  { id: 109, name: "Paneer Masala", category: "Real Spice Paneer Special", price: 230, image: "/images/paneer-masala.png", description: "Homestyle paneer masala.", isVeg: true },
  { id: 110, name: "Paneer Tikka Masala", category: "Real Spice Paneer Special", price: 250, image: "/images/paneer-tikka-masala.png", description: "Paneer tikka in rich masala.", isVeg: true },
  { id: 111, name: "Paneer Kadai", category: "Real Spice Paneer Special", price: 250, image: "/images/paneer-kadai.png", description: "Paneer cooked in kadai gravy.", isVeg: true },
  { id: 112, name: "Paneer Butter Masala", category: "Real Spice Paneer Special", price: 250, image: "/images/paneer-butter-masala.png", description: "Creamy paneer butter masala.", isVeg: true },
  { id: 113, name: "Paneer Cheese Butter Masala", category: "Real Spice Paneer Special", price: 280, image: "/images/paneer-cheese-butter-masala.png", description: "Cheesy paneer butter masala.", isVeg: true },
  { id: 114, name: "Paneer Handi", category: "Real Spice Paneer Special", price: 350, image: "/images/paneer-handi.png", description: "Slow-cooked paneer handi.", isVeg: true },
  { id: 115, name: "Paneer Lasunia", category: "Real Spice Paneer Special", price: 290, image: "/images/paneer-lasunia.png", description: "Paneer lasunia special.", isVeg: true },
  { id: 116, name: "Paneer Chatpata", category: "Real Spice Paneer Special", price: 240, image: "/images/paneer-chatpata.png", description: "Tangy chatpata paneer.", isVeg: true },
  { id: 117, name: "Paneer Toofani", category: "Real Spice Paneer Special", price: 250, image: "/images/paneer-toofani.png", description: "Spicy toofani paneer.", isVeg: true },
  { id: 118, name: "Paneer Lawabdar", category: "Real Spice Paneer Special", price: 280, image: "/images/paneer-lawabdar.png", description: "Rich lawabdar paneer.", isVeg: true },
  { id: 119, name: "Paneer Pasanda", category: "Real Spice Paneer Special", price: 280, image: "/images/paneer-pasanda.png", description: "Paneer pasanda.", isVeg: true },
  { id: 120, name: "Paneer Kolhapuri", category: "Real Spice Paneer Special", price: 250, image: "/images/paneer-kolhapuri.png", description: "Kolhapuri style paneer.", isVeg: true },
  { id: 121, name: "Paneer Bhurji", category: "Real Spice Paneer Special", price: 250, image: "/images/paneer-bhurji.png", description: "Spiced paneer bhurji.", isVeg: true },
];
