export type MenuItem = {
  id: number;
  name: string;
  category: string;
  price: number | null;
  image: string;
  description?: string;
  items?: string[];
  isVeg: boolean;
};

export const categories = [
  "All",
  "Appetizers",
  "Breads",
  "Beverages",
  "Sides",
];

export const menuItems: MenuItem[] = [
  {
    id: 1,
    name: "Masala Papad",
    category: "Appetizers",
    price: 40,
    image: "/images/masala-papad.png",
    description: "Crispy papad with masala seasoning.",
    isVeg: true,
  },
  {
    id: 2,
    name: "Fry Papad",
    category: "Appetizers",
    price: 25,
    image: "/images/fry-papad.png",
    description: "Light and crispy fried papad.",
    isVeg: true,
  },
  {
    id: 3,
    name: "Roasted Papad",
    category: "Appetizers",
    price: 20,
    image: "/images/roasted-papad.png",
    description: "Gently roasted papad.",
    isVeg: true,
  },
  {
    id: 4,
    name: "Chole Bature",
    category: "Breads",
    price: 130,
    image: "/images/chole-bhature.png",
    description: "Fluffy deep-fried bread with spiced chickpea curry.",
    isVeg: true,
  },
  {
    id: 5,
    name: "Pav Bhaji",
    category: "Breads",
    price: 150,
    image: "/images/pav-bhaji.png",
    description: "Mumbai-style spiced mashed vegetables with butter pav.",
    isVeg: true,
  },
  {
    id: 6,
    name: "Aalo Paratha",
    category: "Breads",
    price: 150,
    image: "/images/aalo-paratha.png",
    description: "Potato-stuffed Indian bread, 2 pieces.",
    isVeg: true,
  },
  {
    id: 7,
    name: "Butter Milk",
    category: "Sides",
    price: 30,
    image: "/images/butter-milk.png",
    description: "Fresh chilled buttermilk.",
    isVeg: true,
  },
  {
    id: 8,
    name: "Boondi Raita",
    category: "Sides",
    price: 70,
    image: "/images/boondi-raita.png",
    description: "Yogurt with boondi (tiny fried gram flour balls).",
    isVeg: true,
  },
  {
    id: 9,
    name: "Veg Raita",
    category: "Sides",
    price: 70,
    image: "/images/veg-raita.png",
    description: "Yogurt with mixed vegetables.",
    isVeg: true,
  },
  {
    id: 10,
    name: "Green Salad",
    category: "Sides",
    price: 90,
    image: "/images/green-salad.png",
    description: "Fresh seasonal green salad.",
    isVeg: true,
  },
  {
    id: 11,
    name: "Finger Chips",
    category: "Sides",
    price: 100,
    image: "/images/finger-chips.png",
    description: "Crispy golden potato fries.",
    isVeg: true,
  },
  {
    id: 12,
    name: "Plain Lassi",
    category: "Beverages",
    price: 50,
    image: "/images/plain-lassi.png",
    description: "Traditional yogurt drink.",
    isVeg: true,
  },
  {
    id: 13,
    name: "Patiala Lassi",
    category: "Beverages",
    price: 100,
    image: "/images/patiala-lassi.png",
    description: "Rich and creamy Patiala-style lassi.",
    isVeg: true,
  },
  {
    id: 14,
    name: "Mango Lassi",
    category: "Beverages",
    price: 70,
    image: "/images/mango-lassi.png",
    description: "Creamy yogurt drink with ripe mango.",
    isVeg: true,
  },
  {
    id: 15,
    name: "Strawberry Lassi",
    category: "Beverages",
    price: 70,
    image: "/images/strawberry-lassi.png",
    description: "Refreshing strawberry yogurt drink.",
    isVeg: true,
  },
  {
    id: 16,
    name: "Dry Fruit Lassi",
    category: "Beverages",
    price: 90,
    image: "/images/dry-fruit-lassi.png",
    description: "Lassi enriched with dry fruits and nuts.",
    isVeg: true,
  },
  {
    id: 17,
    name: "Oreo Shake",
    category: "Beverages",
    price: 100,
    image: "/images/oreo-shake.png",
    description: "Creamy shake with crushed Oreo cookies.",
    isVeg: true,
  },
  {
    id: 18,
    name: "Chocolate Shake",
    category: "Beverages",
    price: 100,
    image: "/images/chocolate-shake.png",
    description: "Rich and indulgent chocolate milkshake.",
    isVeg: true,
  },
  {
    id: 19,
    name: "Cold Coffee",
    category: "Beverages",
    price: 80,
    image: "/images/cold-coffee.png",
    description: "Chilled coffee with milk and ice.",
    isVeg: true,
  },
  {
    id: 20,
    name: "Tea",
    category: "Beverages",
    price: 30,
    image: "/images/tea.png",
    description: "Hot Indian tea.",
    isVeg: true,
  },
  {
    id: 21,
    name: "Hot Coffee",
    category: "Beverages",
    price: 50,
    image: "/images/hot-coffee.png",
    description: "Freshly brewed hot coffee.",
    isVeg: true,
  },
  {
    id: 22,
    name: "Hot Milk",
    category: "Beverages",
    price: 60,
    image: "/images/hot-milk.png",
    description: "Hot steamed milk.",
    isVeg: true,
  },
  {
    id: 23,
    name: "Mint Mojito",
    category: "Beverages",
    price: 150,
    image: "/images/mint-mojito.png",
    description: "Refreshing mint mojito with lime and soda.",
    isVeg: true,
  },
  {
    id: 24,
    name: "Fresh Lime Soda",
    category: "Beverages",
    price: 50,
    image: "/images/fresh-lime-soda.png",
    description: "Tangy fresh lime soda.",
    isVeg: true,
  },
  {
    id: 25,
    name: "Dahi",
    category: "Sides",
    price: 50,
    image: "/images/dahi.png",
    description: "Fresh homemade yogurt.",
    isVeg: true,
  },
];